### ISSUE TITLE
Possible duplication in expression and value

### ISSUE THREAD

**Issue by rhinton** [Nic30/hdlConvertor#114]
I see that `HdlValue` can be a `BigInteger`, and `iHdlExpr` can be initialized with a `BigInteger` or `HdlValue`.  Is there a reason for this duplication? 

In other words, `iHdlExpr` can hold an `HdlValue` that is an integer, or it can hold an integer directly.  Why?

**Comment by rhinton** [comment]
Update: Looking in the code, the `iHdlExpr` constructor that takes a `BigInteger` simply wraps it in an `HdlValue`.  I assume the duplicate code paths are for convenience, right?

https://github.com/Nic30/hdlConvertor/blob/83ed705d37e4c5962e75b3b4a1e5a255230c44be/src/hdlObjects/iHdlExpr.cpp#L48

**Comment by Nic30** [comment]
>  for convenience

Yes, but also I do see it as a suboptimal solution, let's merge all in progress work in some branch and let's create a subclass of `iHdlExpr` for each value type and use it instead of `iHdlExpr.data = new HdlValue...` The iHdlValue was meant for something different and currently it only shadows the things.

**Comment by Nic30** [comment]
depends on #115

**Comment by Nic30** [comment]
closing as the referenced code does not exists any more after 4ee2378
